version: '3.7'

services:
  backend:
    build: backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    image: jor2/djangobackend

  frontend:
    build: frontend
    ports:
      - 5000:5000
    image: jor2/flaskfrontend
